### ISSUE TITLE
License regarding the mesh/urdf files in this repo?

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [aionrobotics/r1_ugv_sim#1]
Since the Aion Robotics R1 rover is being widely used in the px4 community, it would greatly benefit the px4 users that use the Aion robotics R1 rover to be able to simulate the model in the PX4 SITL(Software-In-The-Loop) Gazebo simulation. 

I have added a PR in https://github.com/PX4/sitl_gazebo/pull/394 to add support for the model using the mesh files and urdf files in this repo. The video can be found below: 

[![Demo](https://img.youtube.com/vi/cL7ZhvNvV3o/0.jpg)](https://youtu.be/cL7ZhvNvV3o) 

Would it be possible to distribute the files as part of the BSD-3 license of the PX4/sitl_gazebo repo? Since this repo does not contain a license, I wasn't sure how to attribute the credits. I have tried contacting aion robotics through https://www.aionrobotics.com/contact-us, but did not get any reply. 

Thanks,

**Comment by NickNunno** [comment]
Hello @Jaeyoung-Lim [LICENCE.txt](https://github.com/aionrobotics/r1_ugv_sim/blob/master/LICENSE.txt) added to clear ambiguity.

Thank you!
